// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:

        return macos;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVzpCGVwnU965UulEEJ7fI65_IGd8o3Q',
    appId: '1:602267568095:web:22353b6f88b823b329e66a',
    messagingSenderId: '602267568095',
    projectId: 'sales-application-c0d8a',
    authDomain: 'sales-application-c0d8a.firebaseapp.com',
    storageBucket: 'sales-application-c0d8a.appspot.com',
    measurementId: 'G-0766E369E1',
  );



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_LfOdusO2ZhmrR9mNmzV9wC_-MtoKfpg',
    appId: '1:602267568095:android:98e29b73d2c8decd29e66a',
    messagingSenderId: '602267568095',
    projectId: 'sales-application-c0d8a',


    databaseURL: 'https://sales-application-c0d8a-default-rtdb.firebaseio.com',

    storageBucket: 'sales-application-c0d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOh4tj00SICWBl1yqCOoCDfss5L3TD6fo',
    appId: '1:602267568095:ios:fd9421218505755a29e66a',
    messagingSenderId: '602267568095',
    projectId: 'sales-application-c0d8a',

    storageBucket: 'sales-application-c0d8a.appspot.com',
    iosBundleId: 'com.example.salesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOh4tj00SICWBl1yqCOoCDfss5L3TD6fo',
    appId: '1:602267568095:ios:fd9421218505755a29e66a',
    messagingSenderId: '602267568095',
    projectId: 'sales-application-c0d8a',

    databaseURL: 'https://sales-application-c0d8a-default-rtdb.firebaseio.com',
    storageBucket: 'sales-application-c0d8a.appspot.com',
    iosBundleId: 'com.example.salesApplication',
  );
}